require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LectureGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # LectureGroup. As you add validations to LectureGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LectureGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lecture_groups as @lecture_groups" do
      lecture_group = LectureGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lecture_groups).should eq([lecture_group])
    end
  end

  describe "GET show" do
    it "assigns the requested lecture_group as @lecture_group" do
      lecture_group = LectureGroup.create! valid_attributes
      get :show, {:id => lecture_group.to_param}, valid_session
      assigns(:lecture_group).should eq(lecture_group)
    end
  end

  describe "GET new" do
    it "assigns a new lecture_group as @lecture_group" do
      get :new, {}, valid_session
      assigns(:lecture_group).should be_a_new(LectureGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested lecture_group as @lecture_group" do
      lecture_group = LectureGroup.create! valid_attributes
      get :edit, {:id => lecture_group.to_param}, valid_session
      assigns(:lecture_group).should eq(lecture_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LectureGroup" do
        expect {
          post :create, {:lecture_group => valid_attributes}, valid_session
        }.to change(LectureGroup, :count).by(1)
      end

      it "assigns a newly created lecture_group as @lecture_group" do
        post :create, {:lecture_group => valid_attributes}, valid_session
        assigns(:lecture_group).should be_a(LectureGroup)
        assigns(:lecture_group).should be_persisted
      end

      it "redirects to the created lecture_group" do
        post :create, {:lecture_group => valid_attributes}, valid_session
        response.should redirect_to(LectureGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lecture_group as @lecture_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        LectureGroup.any_instance.stub(:save).and_return(false)
        post :create, {:lecture_group => { "title" => "invalid value" }}, valid_session
        assigns(:lecture_group).should be_a_new(LectureGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LectureGroup.any_instance.stub(:save).and_return(false)
        post :create, {:lecture_group => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lecture_group" do
        lecture_group = LectureGroup.create! valid_attributes
        # Assuming there are no other lecture_groups in the database, this
        # specifies that the LectureGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LectureGroup.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => lecture_group.to_param, :lecture_group => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested lecture_group as @lecture_group" do
        lecture_group = LectureGroup.create! valid_attributes
        put :update, {:id => lecture_group.to_param, :lecture_group => valid_attributes}, valid_session
        assigns(:lecture_group).should eq(lecture_group)
      end

      it "redirects to the lecture_group" do
        lecture_group = LectureGroup.create! valid_attributes
        put :update, {:id => lecture_group.to_param, :lecture_group => valid_attributes}, valid_session
        response.should redirect_to(lecture_group)
      end
    end

    describe "with invalid params" do
      it "assigns the lecture_group as @lecture_group" do
        lecture_group = LectureGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LectureGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => lecture_group.to_param, :lecture_group => { "title" => "invalid value" }}, valid_session
        assigns(:lecture_group).should eq(lecture_group)
      end

      it "re-renders the 'edit' template" do
        lecture_group = LectureGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LectureGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => lecture_group.to_param, :lecture_group => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lecture_group" do
      lecture_group = LectureGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => lecture_group.to_param}, valid_session
      }.to change(LectureGroup, :count).by(-1)
    end

    it "redirects to the lecture_groups list" do
      lecture_group = LectureGroup.create! valid_attributes
      delete :destroy, {:id => lecture_group.to_param}, valid_session
      response.should redirect_to(lecture_groups_url)
    end
  end

end
